# Generated by Django 4.2.7 on 2023-12-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='status',
            new_name='completed',
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(default='Medium', max_length=25),
        ),
    ]
